title: Shyam Vijayakumar # your name (or website title) here
#logo: "/images/Shyam.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I have 6.5 years of software engineering experience and a Bachelor's degree in Electrical Engineering and Computer Science from University of California, Berkeley. 
  <br><br>
  Currently, I'm a Senior Software Engineer at Musicians Institute, specializing in full stack Javascript development. 
  <br><br>
  <a href="https://drive.google.com/file/d/1fu0YE4uDYFapgbwMS1Gpcd4gj09cWSHv/view?usp=sharing">View My Resume</a>
  <br/><br/>
  
theme: jekyll-theme-dinky
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
