title: Shyam Vijayakumar # your name (or website title) here
#logo: "/images/Shyam.jpg" # your photo (or logo) here
description: # your text below (remove <br> elements if you don't need line breaks)
  I have 7 years of software engineering experience and a Bachelor's degree in Electrical Engineering and Computer Science from University of California, Berkeley. 
  <br><br>
  Currently, I'm a Software Engineer at Cast and Crew, specializing in full stack Javascript development. 
  <br><br>
  <a href="https://drive.google.com/file/d/1gNaaQ8WFxSvigvtdkXMy3YtoYElcGTwE/view?usp=sharing">View My Resume</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
